# Generated by Django 4.2.28 on 2026-02-11 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_id', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='clients.client')),
            ],
            options={
                'db_table': 'app_client_account',
                'indexes': [models.Index(fields=['client'], name='idx_clientaccount_client'), models.Index(fields=['account_id'], name='idx_clientaccount_account')],
                'unique_together': {('client', 'account_id')},
            },
        ),
    ]
